name: Build Vecx Core

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 pkg-config

      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Build vecx core
        run: |
          source emsdk/emsdk_env.sh
          git clone https://github.com/libretro/libretro-vecx.git
          cd libretro-vecx

          emmake make -f Makefile.libretro platform=emscripten EMSCRIPTEN=1 -j2

          echo "🔍 LISTANDO ARCHIVOS GENERADOS:"
          ls -la

      - name: Build EmulatorJS core
        run: |
          source emsdk/emsdk_env.sh

          git clone https://github.com/EmulatorJS/RetroArch.git --branch next

          echo "🔍 BUSCANDO ARCHIVO .bc"
          find . -name "*.bc"

          cp libretro-vecx/*.bc RetroArch/dist-scripts/ || true

          cd RetroArch
          emmake ./build-emulatorjs.sh

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: vecx-core
          path: EmulatorJS/data/cores/
